### ISSUE TITLE
Error on first launch

### ISSUE THREAD

**Issue by idealley** [openstream/open-social-media-monitoring#1]
Hi, I have tried to install your script. I uploaded all files to the server, then I browsed to it, I got the following error:

Warning: require_once(/home/www/4aa72da8490a218b989404135721fbe9/web/openstream/classes/Option.php) [function.require-once]: failed to open stream: No such file or directory in /home/www/4aa72da8490a218b989404135721fbe9/web/openstream/index.php on line 24

Fatal error: require_once() [function.require]: Failed opening required '/home/www/4aa72da8490a218b989404135721fbe9/web/openstream/classes/Option.php' (include_path='.:/opt/php/lib/php') in /home/www/4aa72da8490a218b989404135721fbe9/web/openstream/index.php on line 24

Sam

**Comment by nickweisser** [comment]
I'm not sure why index.php is trying to load the Option.php class. Please make sure you don't have any other files in the directory where the Open Social Media Monitoring script resides.

**Comment by tim-bezhashvyly** [comment]
Please check the major version change.
