### ISSUE TITLE
Please explain how to install.

### ISSUE THREAD

**Issue by ghost** [openstream/open-social-media-monitoring#10]
Hi,
When I tried to install, I got a prompt for Administrator Logon. 
Where do I obtain the email and password for the same?
Please tell me how do I install this. I'm sorry but I'm relatively new to all of this.
Thanks! :)

**Comment by tim-bezhashvyly** [comment]
Hello Kshitij,

Can you please check if you have /settings.php file?

YES: then delete it and try again.
NO: Check that your DB is not allowing anonymous access.

Regards,
Tim.

**Comment by ghost** [comment]
Hi Tim,
Sorry to bother you again. But I'll write down what I did
I copied the files to my server in folder openstream
Then I ran the url mydomain.com/openstream 
I get this screen. http://web.iiit.ac.in/~kshitijv.ingle/Screenshot.png
Can you give me a step by step procedure to install this. I'd be really grateful.

Update : 
Whenever I run the initial index.php file, I am suggested to run the installer script, and when I click on "Run", I am redirected to the URI : "/installer/run/" , but my server returns a 404, saying the resource doesnot exist.

I am running an apache server on an ubuntu machine, and I confirmed that mod_Rewrite is installed. or very simply, I think my apache server doesnot see the URI as something to be passed to the MVC architecture, rather it thinks it to be a resource present in the file structure :(

Would be glad if you can help me out.

**Comment by tim-bezhashvyly** [comment]
There's something unusual with your server. Let's do a little debugging. You need to edit classes/Application.php file and add `echo` in front of lines 51 and 52. Let me know what output you get.

**Comment by tim-bezhashvyly** [comment]
Please check the major version change.
