### ISSUE TITLE
Can't add projects

### ISSUE THREAD

**Issue by j8kes** [openstream/open-social-media-monitoring#11]
Hi, I've installed and setup, but in the admin interface nothing happens when I try to add a new project.

I click Add Project, 
Fill in the name,
Click Save.

The default admin interface then loads with the Add Project button but no projects.
Any suggestions?

**Comment by tim-bezhashvyly** [comment]
Anything in your apache logs?

**Comment by j8kes** [comment]
I checked, absolutely nothing.

**Comment by tim-bezhashvyly** [comment]
Sorry for taking long to reply. I double-checked everything but can't find a reason why it may not work on your end. Can you please check that `projects` table exists. Additionally you may try to add some debugging code to your `classes/Projects.php` commenting out line 199 and echoing `mysql_error()`.

**Comment by tim-bezhashvyly** [comment]
Please check the major version change.
