### ISSUE TITLE
Install Error: PHP Notice: Undefined index

### ISSUE THREAD

**Issue by mcmenkes** [openstream/open-social-media-monitoring#18]
Hi, 

while installing osmm under Debian Squeeze, i get errors as follows, which are printed out in the config forms for adding values such as email, admin, DB etc. 

[Mon Nov 26 12:18:33 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: authentication in /srv/vhost/my-server.de/open-social-media-monitoring-master/modules/default/controllers/Inde
xController.php on line 9
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: authentication in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index
/index.phtml on line 15
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: authentication in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index
/index.phtml on line 19
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: settings in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index
.phtml on line 23
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml
 on line 27
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml
 on line 31
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml
 on line 35
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml
 on line 39
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml
 on line 43
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: settings in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index
.phtml on line 47
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: settings in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index
.phtml on line 51
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: template in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: template in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 55
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: authentication in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 15, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: authentication in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 19, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: settings in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 23, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 27, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 31, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 35, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 39, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 43, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: settings in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 47, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: settings in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 51, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: template in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 55, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: authentication in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 15, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: authentication in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 19, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: settings in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 23, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 27, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 31, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 35, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 39, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: db in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 43, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: settings in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 47, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: settings in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 51, referer: http://www.my-server.de/open-social-media-monitoring-master/install/
[Mon Nov 26 12:18:34 2012] [error] [client 192.168.50.1] PHP Notice:  Undefined index: template in /srv/vhost/my-server.de/open-social-media-monitoring-master/templates/default/settings/index/index.phtml on line 55, referer: http://www.my-server.de/open-social-media-monitoring-master/install/

If i add the the first config values, osmm will not work properly

=> Do i need extra PHP-Functions ?

Thanks in advance & best regards, 

MCm

**Comment by tim-bezhashvyly** [comment]
Hi, this issue is fixed by my last commit. Sorry for inconveniences.
