### ISSUE TITLE
Installer not running on first load

### ISSUE THREAD

**Issue by fienen** [openstream/open-social-media-monitoring#2]
After uploading the package and going to the URI, rather than getting an installer or anything like that, I get the screen in the screenshot below. It complains about the Application class and some undefined indexes. And none of the other views appear to work, for instance, you can't actually click on 'projects' or 'settings' or anything like that.

I'm running PHP 5.3.5 on a Windows server with MySQL.

Note: I can eliminate the first error by changing:

```
Application::run();
```

in index.php to:

```
$app = new Application();
$app->run();
```

![index.php screenshot](http://i42.tinypic.com/106x400.png)

**Comment by tim-bezhashvyly** [comment]
Please try to switch error reporting level to E_ALL ^ E_NOTICE. Let me know if it helped.

**Comment by tim-bezhashvyly** [comment]
Also just made a commit that is supposed to fix your problem even with your current reporting settings. Please let me know.

**Comment by fienen** [comment]
Thanks, I'll test this out in a bit and let you know.

**Comment by fienen** [comment]
That handled the error messages, but on first run it's still not dropping into the installer.

**Comment by tim-bezhashvyly** [comment]
Interesting.

Looks like the problem is happening because $_SERVER['SCRIPT_NAME'] and $_SERVER['REQUEST_URI'] variables may be different at Windows server. can you please put the print_r($_SERVER) at the top of your index.php and send me the output?

Thanks,
Tim.

**Comment by fienen** [comment]
Array ( [MIBDIRS] => C:/xampp/php/extras/mibs [MYSQL_HOME] => \xampp\mysql\bin [OPENSSL_CONF] => C:/xampp/apache/bin/openssl.cnf [PHP_PEAR_SYSCONF_DIR] => \xampp\php [PHPRC] => \xampp\php [TMP] => \xampp\tmp [HTTP_HOST] => 192.168.2.4 [HTTP_CONNECTION] => keep-alive [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.24 Safari/536.5 [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8 [HTTP_ACCEPT_ENCODING] => gzip,deflate,sdch [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.8 [HTTP_ACCEPT_CHARSET] => ISO-8859-1,utf-8;q=0.7,*;q=0.3 [HTTP_COOKIE] => PHPSESSID=6gea5fj0i4jc85qi99lpgiequ5 [PATH] => C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\TortoiseSVN\bin [SystemRoot] => C:\WINDOWS [COMSPEC] => C:\WINDOWS\system32\cmd.exe [PATHEXT] => .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH [WINDIR] => C:\WINDOWS [SERVER_SIGNATURE] =>
Apache/2.2.17 (Win32) mod_ssl/2.2.17 OpenSSL/0.9.8o PHP/5.3.4 mod_perl/2.0.4 Perl/v5.10.1 Server at 192.168.2.4 Port 80
[SERVER_SOFTWARE] => Apache/2.2.17 (Win32) mod_ssl/2.2.17 OpenSSL/0.9.8o PHP/5.3.4 mod_perl/2.0.4 Perl/v5.10.1 [SERVER_NAME] => 192.168.2.4 [SERVER_ADDR] => 192.168.2.4 [SERVER_PORT] => 80 [REMOTE_ADDR] => 192.168.2.14 [DOCUMENT_ROOT] => C:/xampp/htdocs [SERVER_ADMIN] => postmaster@localhost [SCRIPT_FILENAME] => C:/xampp/htdocs/openstream/index.php [REMOTE_PORT] => 58720 [GATEWAY_INTERFACE] => CGI/1.1 [SERVER_PROTOCOL] => HTTP/1.1 [REQUEST_METHOD] => GET [QUERY_STRING] => [REQUEST_URI] => /openstream/ [SCRIPT_NAME] => /openstream/index.php [PHP_SELF] => /openstream/index.php [REQUEST_TIME] => 1334944514 )

**Comment by fienen** [comment]
And you are right, I installed on a linux server and it went exactly as expected. It's the Windows box that seems to not spin up right.

**Comment by tim-bezhashvyly** [comment]
Actually I think the problem on your windows host was not related to server variables. I guess it was somehow related to anonymous MySQL user account. I would like to diagnose this issue so other people will be able to run the application on they Windows machines. It will be great if you will be able to change the line #31 of classes/Application.php to

``` php
   if($dbHost && $dbUser && $rd = @mysql_connect($dbHost, $dbUser, $dbPassword)){
```

and tell me if it solves the problem. Also please check and confirm that settings.php file doesn't exist.
