### ISSUE TITLE
Disable Projects

### ISSUE THREAD

**Issue by fienen** [openstream/open-social-media-monitoring#4]
Feature request: Give administrators the option to disable crawling for a project, but keep the project stored or archived for reference. Currently, you can only have active projects, or delete them entirely.

**Comment by tim-bezhashvyly** [comment]
Feature implemented.

Note that you have to either reinstall the application completely or to add project_status filed to the projects table to get it running.

 project_status TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT  '1'
