### ISSUE TITLE
bug Installer script

### ISSUE THREAD

**Issue by eternity6** [openstream/open-social-media-monitoring#6]
when you install the program, after completing the registration form, the script returns a blank page. The bug is present within the file Installer.php in the line 89.

change: 

if(count($_POST) == 9){

with:

if(count($_POST) == 10){

according to my opinion this is not the best way to check if a form was filled out and submitted correctly.

**Comment by eternity6** [comment]
another bug always in Installer.php script is on line 76

change
DROP TABLE IF EXISTS '.$_POST['prefix'].'project;
CREATE TABLE IF NOT EXISTS '.$_POST['prefix'].'project (
  project_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  project_name varchar(255) NOT NULL,
  project_status TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT  \'1\'
  PRIMARY KEY (project_id)
);

with:

DROP TABLE IF EXISTS '.$_POST['prefix'].'project;
CREATE TABLE IF NOT EXISTS '.$_POST['prefix'].'project (
  project_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  project_name varchar(255) NOT NULL,
  project_status TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT  \'1\',
  PRIMARY KEY (project_id)
);

you can also use a mysql transaction for control that all query work right.

**Comment by tim-bezhashvyly** [comment]
Hi. Thanks for noticing those errors. I will fix them as soon as I have a time. Meanwhile feel free to make your fork and contribute with better installer code (mine was taken from an really old script).

**Comment by tim-bezhashvyly** [comment]
The bug has been fixed in ver. 0.1.9
