### ISSUE TITLE
From: Invalid date To: Invalid date

### ISSUE THREAD

**Issue by 1nspect0rGadget** [openstream/open-social-media-monitoring#7]
1. I cannot change the date range to say "From: May 31, 2012 To: June 01, 2012" for the Daily  Twitter vs. Facebook graph. It is stuck on 12/31/1969. My keywords are "facebook, ipo"
2. I set up the cron job for every 15 minutes yesterday morning: php ...../openstream/cron.php. I have not gotten any data

Thanks.

**Comment by tim-bezhashvyly** [comment]
Hi Inspector.

Are you using the latest code?

**Comment by 1nspect0rGadget** [comment]
Hey Tim,

I downloaded the ZIP from
http://openstream.github.com/open-social-media-monitoring/
Not sure what version number it is.

Thanks.

Adrian

On Fri, Jun 1, 2012 at 4:36 AM, tim-openstream <
reply@reply.github.com

**Comment by tim-bezhashvyly** [comment]
Hi Adrian.

Sorry about the delay with reply. 
1. The issue with date may be related to the fact you still have no data (do you?)
2. The issue with a cron may be cause by the fact you have your project disabled or cron is not configured correctly (path?).

**Comment by tim-bezhashvyly** [comment]
Please check the major version change.
