### ISSUE TITLE
Interal Server Error 500 on first load

### ISSUE THREAD

**Issue by pcnyla** [openstream/open-social-media-monitoring#8]
Hi there,

I've just uploaded a clean install of all the files but when I go to the URL I get a Server Error... any tips?

Thanks,

Paul

**Comment by nickweisser** [comment]
Please check your web server log for more details about the error and post them here. Thanks.

**Comment by pcnyla** [comment]
Thanks for your reply; the error is:

[Sat Jun 30 15:18:48 2012] [error] [client 31.52.3.194] PHP Fatal error:  Call to undefined function open_table() in /home/awight/social2/classes/Installer.php on line 18

**Comment by tim-bezhashvyly** [comment]
I'm sorry. This is my fault related to migrating towards MVC scheme. I all release the patch in a couple of hours but as a temporary measure you can comment out all 4 occurrences of `open_table()` and `close_table()` functions in classes/Installer.php.

**Comment by tim-bezhashvyly** [comment]
Please check if it fixes your issue.

**Comment by pcnyla** [comment]
Certainly does! Many thanks. Do I need to obtain an alchemy api key?

**Comment by tim-bezhashvyly** [comment]
Alchemy API key is required if you are planning to use keywords in specific language.

**Comment by tim-bezhashvyly** [comment]
Please check the major version change.
