### ISSUE TITLE
Improve language support

### ISSUE THREAD

**Issue by leonaressi** [openstream/open-social-media-monitoring#9]
I've tweaked the language list at Block/Keywords/Edit.php to include another languages from the Twitter official supported languages (https://api.twitter.com/1/help/languages.json)

And I've come into this:

$avail_lang = array('all' => '', 'English' => 'en', 'Turkish' => 'tr', 'Simplified Chinese' => 'zh-cn', 'Japanese' => 'ja', 'Filipino' => 'fil', 'Indonesian' => 'id', 'Urdu' => 'ur', 'Thai' => 'th', 'Spanish' => 'es', 'Italian' => 'it', 'Swedish' => 'sv', 'Hebrew' => 'he', 'Polish' => 'pl', 'Korean' => 'ko', 'Malay' => 'msa', 'French' => 'fr', 'Arabic' => 'ar', 'Portuguese' => 'pt', 'Dutch' => 'nl', 'Norwegian' => 'no', 'German' => 'de', 'Danish' => 'da', 'Hindi' => 'hi', 'Russian' => 'ru', 'Finnish' => 'fi', 'Traditional Chinese' => 'zh-tw', 'Hungarian' => 'hu', 'Farsi' => 'fa');

But some queries using 'pt' language didn't work, maybe because openstream doens't query directly the twitter api, I don't know... Should I try an Alchemy supported languages list?

Any Ideas?

**Comment by tim-bezhashvyly** [comment]
Hello Leo,

The application is querying directly to Twitter API. Can you please give an example of query you have problem with?

Regards,
Tim.

**Comment by leonaressi** [comment]
Hi Tim, 

I'm trying to do this search:
https://twitter.com/#!/search/_dp6%20lang%3Apt

Query: "_dp6" Lang: pt

In Openstream it returns 0 results always.

I din't had time to try to debug that. But maybe for you it's a lot easier as you know all the souce code :)
If you need any further help on this please let me know!

Regards
Leo

**Comment by tim-bezhashvyly** [comment]
I just created a `_dp6` query with lang=pt and got plenty results:

![screenshot](http://www.open-social-media-monitoring.net/tim/Screen%20Shot%202012-08-09%20at%202.35.02%20PM.png)

**Comment by leonaressi** [comment]
You're right! It worked! 
I don't know what happened before, maybe the cron job could be broked.
Thanks!

Do you want me to commit these $avail_lang mod to Edit.php?

**Comment by tim-bezhashvyly** [comment]
No need. We will be changing it soon.
